### ISSUE TITLE
Can not upload file using ISaver error is (com.microsoft.onedrivesdk.saver.SaverException)

### ISSUE THREAD

**Issue by UmeshBaldaniya46** [OneDrive/onedrive-picker-android#21]
I am not able to upload file on onedrive
I did not  change any code, added file read & write run time permissions to sample app.
I have putt on my APPID on ample app but I still get an "NoFileSpecifiedError".

 File exist /storage/emulated/0/MyFile.txt
fileUri file:///storage/emulated/0/MyFile.txt

error is com.microsoft.onedrivesdk.saver.SaverException
at com.microsoft.onedrivesdk.saver.Saver.handleSave(Saver.java:110)
at com.example.onedrivesdk.saversample.SaverMain.onActivityResult(SaverMain.java:116)

![screenshot_20171116-123122](https://user-images.githubusercontent.com/27193416/32884245-b0799dcc-cadf-11e7-810d-cc4cb749458d.png)

**Comment by ahsan7766** [comment]
Getting Same issue even every uri scheme i follow and debug the app many times. All is perfect but still getting the com.microsoft.onedrivesdk.saver.SaverException with file not specified error .

**Comment by LogeshwariMurugan** [comment]
Im following the same steps given by the Microsoft official portal. but still same issue exists.
NoFileSuspected issue and fulldebugger log null

**Comment by frackinfrell** [comment]
I am also getting this error when using Saver.  NoFileSpecified, even though I thoroughly tested that the file exists and has the correct URI.  Can someone from Microsoft please take a look.

**Comment by peternied** [comment]
@frackinfrell Heya, thanks for summoning me, I don't work at Microsoft anymore and same with Dabo.  I'll add some folks and that might still be around...

@daspek @ificator Someone from there OneDrive Android client might be able to help respond to these questions if you could send it their way.

**Comment by ShaydenV** [comment]
Any chance this issue has been solved?

If not could we get an answer. From the testing I have done it seems the problem lies with the changes in the way Android is handling Intents and file permissions.

**Comment by hanselip** [comment]
@peternied I can take a look at this one

**Comment by rameez-sgi** [comment]
If some has solved this problem please update
